In [2]:
import pandas as pd

In [3]:
# make dataset with just rupestris and riparia
species = pd.read_csv('species_noOutgroupOrHybrids_prediction_dataset.csv')
species.head()

,Instance,Class,x1,y1,x2,y2,x3,y3,x4,y4,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,0,Vitis_acerifolia,579.014742,49.669286,564.117010,34.562869,586.781135,-8.117120,606.032488,-52.232172,...,-773.417167,530.360659,-1338.595312,-296.648911,-788.502868,-421.580330,-878.484789,-733.599371,-608.863391,-1612.438872
1,1,Vitis_aestivalis,622.384266,158.865807,605.478280,137.443677,614.666475,111.062108,642.965277,89.000383,...,-725.211055,343.277655,-1028.649169,-398.067197,-729.232075,-398.355997,-911.901514,-677.709890,-1157.567630,-1652.086177
2,2,Vitis_riparia,584.824913,207.115491,569.123583,164.040784,616.675270,113.001928,677.797976,66.534166,...,-589.139358,331.309077,-1035.774029,-448.443256,-715.676977,-300.604021,-865.491969,-611.708338,-1379.906517,-1614.081403
3,3,Vitis_acerifolia,585.609852,216.778212,568.549214,174.651328,581.563425,114.867125,639.639037,60.326687,...,-717.318142,274.452196,-1178.749422,-518.663464,-794.905709,-317.480363,-897.419201,-587.381767,-1143.685860,-1598.494304
4,4,Vitis_aestivalis,530.039098,111.300539,491.118785,77.735749,486.645484,20.775763,554.143172,-18.328012,...,-665.639109,478.490939,-1140.663125,-310.663543,-593.900401,-346.297023,-873.354059,-561.588170,-930.520913,-1909.580628

In [4]:
# drop everything but rupestris and riparia
for index,row in species.iterrows():
    if row['Class'] != 'Vitis_rupestris' and row['Class'] != 'Vitis_riparia':
        species.drop(labels=index,axis=0,inplace=True)
species.head()

,Instance,Class,x1,y1,x2,y2,x3,y3,x4,y4,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
2,2,Vitis_riparia,584.824913,207.115491,569.123583,164.040784,616.675270,113.001928,677.797976,66.534166,...,-589.139358,331.309077,-1035.774029,-448.443256,-715.676977,-300.604021,-865.491969,-611.708338,-1379.906517,-1614.081403
5,5,Vitis_riparia,618.240685,34.553808,594.384078,16.671759,595.305986,-15.870612,621.519559,-53.013824,...,-839.234352,561.409325,-1371.092294,-353.672002,-684.099119,-430.909666,-867.568183,-834.306978,-457.256396,-1196.581820
6,6,Vitis_riparia,625.083066,132.706216,591.790498,107.034696,596.223391,65.608256,632.751977,25.626178,...,-767.758292,475.377358,-1254.389477,-260.402230,-657.833405,-419.928871,-874.750767,-638.277585,-860.717795,-1705.423237
7,7,Vitis_riparia,582.384739,134.769266,559.105568,123.509775,562.988882,88.247323,599.575380,57.414983,...,-596.167407,462.931631,-1112.110342,-385.412881,-727.745450,-386.717115,-835.407407,-643.454272,-1125.473154,-1805.704622
8,8,Vitis_riparia,622.471381,146.402238,596.314545,114.394458,597.502202,80.116202,626.507629,46.376853,...,-729.636738,462.463526,-1138.149098,-353.720661,-796.031792,-386.344236,-893.226197,-694.971601,-869.918714,-1621.190895

In [5]:
# write out the file 
species.to_csv('species_RupRip_prediction.csv',index=False)