**README** <br>
In order to run the following notebook, please clone the repository located at https://github.com/jdevenegas/plb_midterm. Navigate to this folder on your machine in order to run the following. <br>
***Important note:*** This script was written for Mac OSX, and may not be compatible with Windows. Before publication we would work to ensure that it works on both Mac and Windows, but lacked the necessary time for troubleshooting before the midterm was due.

**1. Data wrangling and csv formatting** <br>
Several steps were undergone to format data for this pipeline and for each type of prediction. <br>
(a) observe given data, fix typos, and get rid of columns that aren't going to be used as features <br>
(b) create csv's for each prediction type, getting rid of irrelevant labels to that prediction type <br>
(c) replace integer labels with equivalent strings (for compatability with pipeline) <br>

Throughout, we observe what the smallest classes are in order to know how many instances each class has in our balanced training set.

**1A. Observe data, fix typos, and get rid of PC columns**

In [10]:
import numpy as np
import pandas as pd

In [11]:
# import df's
base = pd.read_csv('Procrustes_base.csv')
tips = pd.read_csv('Procrustes_tips.csv')

In [12]:
# observe geneal structure of data
base.head()

,base_vine,vine,year,vine_year,species,from_tip,from_base,count,tip_vine,PC1,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,10x1583,1583,2013,1583x2013,Vitis_acerifolia,8,10,17,8x1583,-0.873498,...,-773.417167,530.360659,-1338.595312,-296.648911,-788.502868,-421.580330,-878.484789,-733.599371,-608.863391,-1612.438872
1,10x237621,237621,2013,237621x2013,Vitis_aestivalis,6,10,15,6x237621,0.542626,...,-725.211055,343.277655,-1028.649169,-398.067197,-729.232075,-398.355997,-911.901514,-677.709890,-1157.567630,-1652.086177
2,10x313922,313922,2013,313922x2013,Vitis_riparia,2,10,11,2x313922,1.274040,...,-589.139358,331.309077,-1035.774029,-448.443256,-715.676977,-300.604021,-865.491969,-611.708338,-1379.906517,-1614.081403
3,10x318684,318684,2013,318684x2013,Vitis_acerifolia,2,10,11,2x318684,0.634560,...,-717.318142,274.452196,-1178.749422,-518.663464,-794.905709,-317.480363,-897.419201,-587.381767,-1143.685860,-1598.494304
4,10x483138,483138,2013,483138x2013,Vitis_aestivalis,4,10,13,4x483138,-0.716141,...,-665.639109,478.490939,-1140.663125,-310.663543,-593.900401,-346.297023,-873.354059,-561.588170,-930.520913,-1909.580628

In [13]:
# Remove weird species names.
print(base.species.unique())

# There exist rows with species== 'Vitis_sp.' but we need to get rid of the period

base['species'] = np.where((base.species == 'Vitis_sp.'),'Vitis_sp',base.species)
tips['species'] = np.where((tips.species == 'Vitis_sp.'),'Vitis_sp',tips.species)

# There are some Vitis_x_novae-angliae and some Vitis_x_novae_angliae

base['species'] = np.where((base.species == 'Vitis_x_novae-angliae'),'Vitis_x_novae_angliae',base.species)
tips['species'] = np.where((tips.species == 'Vitis_x_novae-angliae'),'Vitis_x_novae_angliae',tips.species)

['Vitis_acerifolia' 'Vitis_aestivalis' 'Vitis_riparia' 'Vitis_vulpina'
 'Vitis_coignetiae' 'Vitis_labrusca' 'Vitis_cinerea' 'Vitis_x_doaniana'
 'Vitis_rupestris' 'Vitis_sp' 'Vitis_amurensis' 'Vitis_palmata'
 'Vitis_x_novae_angliae' 'Vitis_x_champinii' 'Vitis_x_andersonii'
 'Ampelopsis_brevipedunculata' 'Vitis_sp.' 'Vitis_x_novae-angliae']

In [14]:
# observe what columns are contained in dfs 
print('Procrustes_base.csv column names are: {}'.format(list(base.columns)))

Procrustes_base.csv column names are: ['base_vine', 'vine', 'year', 'vine_year', 'species', 'from_tip', 'from_base', 'count', 'tip_vine', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10', 'PC11', 'PC12', 'PC13', 'PC14', 'PC15', 'PC16', 'PC17', 'PC18', 'PC19', 'PC20', 'PC21', 'PC22', 'PC23', 'PC24', 'PC25', 'PC26', 'PC27', 'PC28', 'PC29', 'PC30', 'PC31', 'PC32', 'PC33', 'PC34', 'PC35', 'PC36', 'PC37', 'PC38', 'PC39', 'PC40', 'PC41', 'PC42', 'x1', 'y1', 'x2', 'y2', 'x3', 'y3', 'x4', 'y4', 'x5', 'y5', 'x6', 'y6', 'x7', 'y7', 'x8', 'y8', 'x9', 'y9', 'x10', 'y10', 'x11', 'y11', 'x12', 'y12', 'x13', 'y13', 'x14', 'y14', 'x15', 'y15', 'x16', 'y16', 'x17', 'y17', 'x18', 'y18', 'x19', 'y19', 'x20', 'y20', 'x21', 'y21']

In [15]:
print('Procrustes_tips.csv column names are: {}'.format(list(tips.columns)))

Procrustes_tips.csv column names are: ['tip_vine', 'vine', 'year', 'vine_year', 'species', 'from_tip', 'from_base', 'count', 'base_vine', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10', 'PC11', 'PC12', 'PC13', 'PC14', 'PC15', 'PC16', 'PC17', 'PC18', 'PC19', 'PC20', 'PC21', 'PC22', 'PC23', 'PC24', 'PC25', 'PC26', 'PC27', 'PC28', 'PC29', 'PC30', 'PC31', 'PC32', 'PC33', 'PC34', 'PC35', 'PC36', 'PC37', 'PC38', 'PC39', 'PC40', 'PC41', 'PC42', 'x1', 'y1', 'x2', 'y2', 'x3', 'y3', 'x4', 'y4', 'x5', 'y5', 'x6', 'y6', 'x7', 'y7', 'x8', 'y8', 'x9', 'y9', 'x10', 'y10', 'x11', 'y11', 'x12', 'y12', 'x13', 'y13', 'x14', 'y14', 'x15', 'y15', 'x16', 'y16', 'x17', 'y17', 'x18', 'y18', 'x19', 'y19', 'x20', 'y20', 'x21', 'y21']

In [16]:
# get rid of columns with data irrelevant to ML 
for col in list(base.columns):
    if 'PC' in col:
        base.drop(labels=col,axis=1,inplace=True)
        
for col in list(tips.columns):
    if 'PC' in col:
        tips.drop(labels=col,axis=1,inplace=True)

In [17]:
# check that columns were successfully eliminated
base.head()

,base_vine,vine,year,vine_year,species,from_tip,from_base,count,tip_vine,x1,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,10x1583,1583,2013,1583x2013,Vitis_acerifolia,8,10,17,8x1583,579.014742,...,-773.417167,530.360659,-1338.595312,-296.648911,-788.502868,-421.580330,-878.484789,-733.599371,-608.863391,-1612.438872
1,10x237621,237621,2013,237621x2013,Vitis_aestivalis,6,10,15,6x237621,622.384266,...,-725.211055,343.277655,-1028.649169,-398.067197,-729.232075,-398.355997,-911.901514,-677.709890,-1157.567630,-1652.086177
2,10x313922,313922,2013,313922x2013,Vitis_riparia,2,10,11,2x313922,584.824913,...,-589.139358,331.309077,-1035.774029,-448.443256,-715.676977,-300.604021,-865.491969,-611.708338,-1379.906517,-1614.081403
3,10x318684,318684,2013,318684x2013,Vitis_acerifolia,2,10,11,2x318684,585.609852,...,-717.318142,274.452196,-1178.749422,-518.663464,-794.905709,-317.480363,-897.419201,-587.381767,-1143.685860,-1598.494304
4,10x483138,483138,2013,483138x2013,Vitis_aestivalis,4,10,13,4x483138,530.039098,...,-665.639109,478.490939,-1140.663125,-310.663543,-593.900401,-346.297023,-873.354059,-561.588170,-930.520913,-1909.580628

In [18]:
tips.head()

,tip_vine,vine,year,vine_year,species,from_tip,from_base,count,base_vine,x1,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,10x1583,1583,2013,1583x2013,Vitis_acerifolia,10,8,17,8x1583,621.386222,...,-740.348327,491.431551,-1184.429944,-422.381192,-450.863223,-349.951396,-804.028509,-696.881267,-680.636268,-1481.073793
1,10x237621,237621,2013,237621x2013,Vitis_aestivalis,10,6,15,6x237621,590.089436,...,-590.009595,549.499758,-1083.626071,-347.969251,-652.867385,-330.876278,-953.816805,-623.349414,-804.172437,-1636.908782
2,10x313922,313922,2013,313922x2013,Vitis_riparia,10,2,11,2x313922,624.843279,...,-754.952214,67.117755,-907.840317,-370.003450,-406.661820,-375.594704,-882.403842,-579.516907,-1200.748501,-1268.151490
3,10x318684,318684,2013,318684x2013,Vitis_acerifolia,10,2,11,2x318684,653.019738,...,-606.252556,340.093733,-893.319459,-103.861178,-511.703252,-348.144917,-916.420517,-704.653492,-1112.899238,-1378.834754
4,10x483138,483138,2013,483138x2013,Vitis_aestivalis,10,4,13,4x483138,518.066503,...,-622.976929,513.871339,-1241.950482,-123.720425,-40.123246,-191.404554,-678.779259,-795.380769,-942.817307,-1658.064377

**1B. Create csv's for each prediction type**

In [19]:
# drop labels and rename class column
# using base_vine or tip_vine as the unique identifier for all samples
# prediction of species
species = base.copy()
species.drop(labels=['vine','year','vine_year','from_tip','from_base','count','tip_vine'],axis=1,inplace=True)
species.rename(columns={'species':'Class'},inplace=True)

# prediction of year
year = base.copy()
year.drop(labels=['vine','vine_year','species','from_tip','from_base','count','tip_vine'],axis=1,inplace=True)
year.rename(columns={'year':'Class'},inplace=True)

# prediction of node from base 
nodeBase = base.copy()
nodeBase.drop(labels=['vine','year','vine_year','species','from_tip','count','tip_vine'],axis=1,inplace=True)
nodeBase.rename(columns={'from_base':'Class'},inplace=True)

# prediction of node from tip
nodeTip = tips.copy()
nodeTip.drop(labels=['vine','year','vine_year','species','from_base','count','base_vine'],axis=1,inplace=True)
nodeTip.rename(columns={'from_tip':'Class'},inplace=True)

In [20]:
# check for duplicate ID's -- need to make sure each instance has a unique identifier
IDs = {}
for index,row in species.iterrows():
    if row['base_vine'] not in IDs:
        IDs[row['base_vine']] = 1
    else: IDs[row['base_vine']] += 1

#for key in IDs:
    #if IDs[key] != 1:
        #print(key)
# the above code is commented out because it would appear that every ID has 3 instances!

# base_vine and tip_vine are not unique identifiers because there is data from three years 
# use numerical index as instance identifiers 
# drop base_vine and tip_vine
species.drop(labels='base_vine',axis=1,inplace=True)
year.drop(labels='base_vine',axis=1,inplace=True)
nodeBase.drop(labels='base_vine',axis=1,inplace=True)
nodeTip.drop(labels='tip_vine',axis=1,inplace=True)

In [21]:
# check what species we have 
speciesDict={}
for index,row in species.iterrows():
    if row['Class'] not in speciesDict:
        speciesDict[row['Class']]=1
    else: speciesDict[row['Class']] +=1
            
print(speciesDict)

{'Vitis_acerifolia': 381, 'Vitis_aestivalis': 168, 'Vitis_riparia': 1971, 'Vitis_vulpina': 258, 'Vitis_coignetiae': 60, 'Vitis_labrusca': 738, 'Vitis_cinerea': 618, 'Vitis_x_doaniana': 30, 'Vitis_rupestris': 603, 'Vitis_sp': 342, 'Vitis_amurensis': 378, 'Vitis_palmata': 66, 'Vitis_x_novae_angliae': 24, 'Vitis_x_champinii': 18, 'Vitis_x_andersonii': 24, 'Ampelopsis_brevipedunculata': 21}

In [22]:
# drop hybrids
hybrids = ['Vitis_x_doaniana','Vitis_x_novae_angliae','Vitis_x_champinii','Vitis_x_andersonii']
outgroup = 'Ampelopsis_brevipedunculata'
species_noHybrids = species.copy()
for hybrid in hybrids:
    indices = species_noHybrids.index[species_noHybrids['Class'] == hybrid].tolist()
    species_noHybrids.drop(index=indices,inplace=True)

In [23]:
# check that hybrids are gone
species_noHybridsDict={}
for index,row in species_noHybrids.iterrows():
    if row['Class'] not in species_noHybridsDict:
        species_noHybridsDict[row['Class']]=1
    else: species_noHybridsDict[row['Class']] +=1
            
print(species_noHybridsDict)

{'Vitis_acerifolia': 381, 'Vitis_aestivalis': 168, 'Vitis_riparia': 1971, 'Vitis_vulpina': 258, 'Vitis_coignetiae': 60, 'Vitis_labrusca': 738, 'Vitis_cinerea': 618, 'Vitis_rupestris': 603, 'Vitis_sp': 342, 'Vitis_amurensis': 378, 'Vitis_palmata': 66, 'Ampelopsis_brevipedunculata': 21}

In [24]:
# make another that excludes outgroup
outgroup = 'Ampelopsis_brevipedunculata'
species_noOutgroup = species_noHybrids.copy()
indices_noOutgroup = species_noOutgroup.index[species_noOutgroup['Class'] == outgroup].tolist()
species_noOutgroup.drop(index=indices_noOutgroup,inplace=True)

species_noOutgroupDict = {}
for index,row in species_noOutgroup.iterrows():
    if row['Class'] not in species_noOutgroupDict:
        species_noOutgroupDict[row['Class']]=1
    else: species_noOutgroupDict[row['Class']] +=1
            
print(species_noOutgroupDict)

{'Vitis_acerifolia': 381, 'Vitis_aestivalis': 168, 'Vitis_riparia': 1971, 'Vitis_vulpina': 258, 'Vitis_coignetiae': 60, 'Vitis_labrusca': 738, 'Vitis_cinerea': 618, 'Vitis_rupestris': 603, 'Vitis_sp': 342, 'Vitis_amurensis': 378, 'Vitis_palmata': 66}

In [25]:
# write out the files
species.to_csv('species_prediction_dataset.csv',index=True,index_label='Instance')
species_noHybrids.to_csv('species_noHybrids_prediction_dataset.csv',index=True,index_label='Instance')
species_noOutgroup.to_csv('species_noOutgroupOrHybrids_prediction_dataset.csv',index=True,index_label='Instance')
year.to_csv('year_prediction_dataset.csv',index=True,index_label='Instance')
nodeBase.to_csv('nodes_from_base_prediction_dataset.csv',index=True,index_label='Instance')
nodeTip.to_csv('nodes_from_trip_prediction_dataset.csv',index=True,index_label='Instance')

In [26]:
# make dataset with just rupestris and riparia
species = pd.read_csv('species_noOutgroupOrHybrids_prediction_dataset.csv')
species.head()

,Instance,Class,x1,y1,x2,y2,x3,y3,x4,y4,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,0,Vitis_acerifolia,579.014742,49.669286,564.117010,34.562869,586.781135,-8.117120,606.032488,-52.232172,...,-773.417167,530.360659,-1338.595312,-296.648911,-788.502868,-421.580330,-878.484789,-733.599371,-608.863391,-1612.438872
1,1,Vitis_aestivalis,622.384266,158.865807,605.478280,137.443677,614.666475,111.062108,642.965277,89.000383,...,-725.211055,343.277655,-1028.649169,-398.067197,-729.232075,-398.355997,-911.901514,-677.709890,-1157.567630,-1652.086177
2,2,Vitis_riparia,584.824913,207.115491,569.123583,164.040784,616.675270,113.001928,677.797976,66.534166,...,-589.139358,331.309077,-1035.774029,-448.443256,-715.676977,-300.604021,-865.491969,-611.708338,-1379.906517,-1614.081403
3,3,Vitis_acerifolia,585.609852,216.778212,568.549214,174.651328,581.563425,114.867125,639.639037,60.326687,...,-717.318142,274.452196,-1178.749422,-518.663464,-794.905709,-317.480363,-897.419201,-587.381767,-1143.685860,-1598.494304
4,4,Vitis_aestivalis,530.039098,111.300539,491.118785,77.735749,486.645484,20.775763,554.143172,-18.328012,...,-665.639109,478.490939,-1140.663125,-310.663543,-593.900401,-346.297023,-873.354059,-561.588170,-930.520913,-1909.580628

In [27]:
# drop everything but rupestris and riparia
for index,row in species.iterrows():
    if row['Class'] != 'Vitis_rupestris' and row['Class'] != 'Vitis_riparia':
        species.drop(labels=index,axis=0,inplace=True)
species.head()

,Instance,Class,x1,y1,x2,y2,x3,y3,x4,y4,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
2,2,Vitis_riparia,584.824913,207.115491,569.123583,164.040784,616.675270,113.001928,677.797976,66.534166,...,-589.139358,331.309077,-1035.774029,-448.443256,-715.676977,-300.604021,-865.491969,-611.708338,-1379.906517,-1614.081403
5,5,Vitis_riparia,618.240685,34.553808,594.384078,16.671759,595.305986,-15.870612,621.519559,-53.013824,...,-839.234352,561.409325,-1371.092294,-353.672002,-684.099119,-430.909666,-867.568183,-834.306978,-457.256396,-1196.581820
6,6,Vitis_riparia,625.083066,132.706216,591.790498,107.034696,596.223391,65.608256,632.751977,25.626178,...,-767.758292,475.377358,-1254.389477,-260.402230,-657.833405,-419.928871,-874.750767,-638.277585,-860.717795,-1705.423237
7,7,Vitis_riparia,582.384739,134.769266,559.105568,123.509775,562.988882,88.247323,599.575380,57.414983,...,-596.167407,462.931631,-1112.110342,-385.412881,-727.745450,-386.717115,-835.407407,-643.454272,-1125.473154,-1805.704622
8,8,Vitis_riparia,622.471381,146.402238,596.314545,114.394458,597.502202,80.116202,626.507629,46.376853,...,-729.636738,462.463526,-1138.149098,-353.720661,-796.031792,-386.344236,-893.226197,-694.971601,-869.918714,-1621.190895

In [28]:
# write out the file 
species.to_csv('species_RupRip_prediction.csv',index=False)



**1C. Replacing integer labels with equivalent strings**

In [29]:
# replace year numbers with strings 
year = pd.read_csv('year_prediction_dataset.csv')
year.replace(to_replace=[2013,2015,2016],value=['year2013','year2015','year2016'],inplace=True)
year.to_csv('year_strings_prediction_dataset.csv',index=False)
# check that replacement worked
year.head()

,Instance,Class,x1,y1,x2,y2,x3,y3,x4,y4,...,x17,y17,x18,y18,x19,y19,x20,y20,x21,y21
0,0,year2013,579.014742,49.669286,564.117010,34.562869,586.781135,-8.117120,606.032488,-52.232172,...,-773.417167,530.360659,-1338.595312,-296.648911,-788.502868,-421.580330,-878.484789,-733.599371,-608.863391,-1612.438872
1,1,year2013,622.384266,158.865807,605.478280,137.443677,614.666475,111.062108,642.965277,89.000383,...,-725.211055,343.277655,-1028.649169,-398.067197,-729.232075,-398.355997,-911.901514,-677.709890,-1157.567630,-1652.086177
2,2,year2013,584.824913,207.115491,569.123583,164.040784,616.675270,113.001928,677.797976,66.534166,...,-589.139358,331.309077,-1035.774029,-448.443256,-715.676977,-300.604021,-865.491969,-611.708338,-1379.906517,-1614.081403
3,3,year2013,585.609852,216.778212,568.549214,174.651328,581.563425,114.867125,639.639037,60.326687,...,-717.318142,274.452196,-1178.749422,-518.663464,-794.905709,-317.480363,-897.419201,-587.381767,-1143.685860,-1598.494304
4,4,year2013,530.039098,111.300539,491.118785,77.735749,486.645484,20.775763,554.143172,-18.328012,...,-665.639109,478.490939,-1140.663125,-310.663543,-593.900401,-346.297023,-873.354059,-561.588170,-930.520913,-1909.580628

In [31]:
 # how many nodes are there?
base_classes = nodeBase['Class'].unique()
tip_classes = nodeTip['Class'].unique()
print('Base nodes: {} Tip nodes: {}'.format(base_classes,tip_classes))

Base nodes: [10 11 12 13 14  1  2  3  4  5  6  7  8  9] Tip nodes: [10 11 12 13 14  1  2  3  4  5  6  7  8  9]

In [52]:
# replace integer labels with strings
nodeBase.replace(to_replace = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],value=['node1','node2','node3','node4','node5','node6',\
                                                                      'node7','node8','node9','node10','node11','node12',\
                                                                      'node13','node14'],inplace=True)
nodeTip.replace(to_replace = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],value=['node1','node2','node3','node4','node5','node6',\
                                                                      'node7','node8','node9','node10','node11','node12',\
                                                                      'node13','node14'],inplace=True)

# write out files 
nodeBase.to_csv('nodes_from_base_strings_prediction_dataset.csv',index=True,index_label='Instance')
nodeTip.to_csv('nodes_from_tip_strings_prediction_dataset.csv',index=True,index_label='Instance')

In [8]:
# check what the smallest group is and how many are in it: year
import csv 
num_classes_year = {}
with open('year_strings_prediction_dataset.csv') as inputf:
    reader = csv.DictReader(inputf)
    
    for row in reader: 
        if row['Class'] not in num_classes_year:
            num_classes_year[row['Class']]=1
        else: num_classes_year[row['Class']] +=1
            
print(num_classes_year)

{'year2013': 1900, 'year2015': 1900, 'year2016': 1900}

In [33]:
# check what the smallest group is and how many are in it: nodes from base
num_classes_base = {}
with open('nodes_from_base_strings_prediction_dataset.csv') as inputf:
    reader = csv.DictReader(inputf)
    
    for row in reader: 
        if row['Class'] not in num_classes_base:
            num_classes_base[row['Class']]=1
        else: num_classes_base[row['Class']] +=1
            
print(num_classes_base)

{'node10': 246, 'node11': 129, 'node12': 51, 'node13': 15, 'node14': 3, 'node1': 639, 'node2': 597, 'node3': 606, 'node4': 621, 'node5': 615, 'node6': 603, 'node7': 606, 'node8': 552, 'node9': 417}

In [34]:
# check what the smallest group is and how many are in it: nodes from tip
num_classes_tip = {}
with open('nodes_from_tip_strings_prediction_dataset.csv') as inputf:
    reader = csv.DictReader(inputf)
    
    for row in reader: 
        if row['Class'] not in num_classes_tip:
            num_classes_tip[row['Class']]=1
        else: num_classes_tip[row['Class']] +=1
            
print(num_classes_tip)

{'node10': 243, 'node11': 126, 'node12': 51, 'node13': 15, 'node14': 3, 'node1': 621, 'node2': 621, 'node3': 630, 'node4': 633, 'node5': 627, 'node6': 609, 'node7': 585, 'node8': 537, 'node9': 408}

In [54]:
# have to drop node14 because the pipeline requires 3-fold validation and throws the following error:
# ValueError: Requesting 3-fold cross-validation but provided less than 3 examples for at least one class.
nodesBase_strings = pd.read_csv('nodes_from_base_strings_prediction_dataset.csv')
nodesTip_strings = pd.read_csv('nodes_from_tip_strings_prediction_dataset.csv')

# get indices of rows to drop
indBase = nodesBase_strings[nodesBase_strings['Class'] == 'node14' ].index
indTip = nodesTip_strings[nodesTip_strings['Class'] == 'node14' ].index

# drop the rows
nodesBase_strings.drop(indBase,inplace=True)
nodesTip_strings.drop(indTip,inplace=True)

# rewrite out 
nodesBase_strings.to_csv('nodes_from_base_strings_prediction_dataset.csv',index=False)
nodesTip_strings.to_csv('nodes_from_tip_strings_prediction_dataset.csv',index=False)

    
**2. Using SVM to predict species based on x-y coordinates** <br>
Christina Azodi's ML-pipeline is used in this script. In order to be able to run the following, please navigate to https://github.com/azodichr/ML-Pipeline and follow the instructions in the readme in order to set up the correct environment to run the pipeline. Then clone the pipeline to your machine. <br>
The pipeline entails two steps as we ran it. First, we created a testing subset of 10% of the data, using the script test_set.py. We then ran ML_correlation.py in order to train our model. <br>

*Note:* the file structure for the following is: one folder called GitHub, which contains both ML-Pipeline and plb_midterm. Please be sure to check that the file paths are correct for your machine and for wherever you cloned the repositories. <br>

In this notebook, you will see that for the species and year analyses, the file path is ~/GitHub/ML-Pipeline, but for the node analyses, the folder is called SL-ML-Pipeline. This is because the size of the smallest groups of nodes (3 instances of the 14th node) threw an error in the original pipeline, and because I have other forks of this pipeline cloned to my machine, I had to make a directory with a different name (and didn't have time to let everything run again from the new directory). When you clone the repo, the default folder name will be ML-Pipeline, and given that you have the correct file path to that folder, you will be able to run everything, as bus have been fixed in Christina's branch of the pipeline. <br>

Additionally, this pipeline defaults to 10 reps of grid search and 100 reps of model training. Here, for the sake of time, and for readability of the notebook, 5 reps of grid search and 10 reps of training have been specified. For publication purposes, these can later be returned to default and re-run.

**2A. Predicting Species** <br>
Species were predicted in the following way: <br>
(i) Just *V. rupestris* and *V. riparia* were predicted, in order to test whether x-y coordinates would be good features. *rupestris* and *riparia* are the most morphologically distinct species, and we hypothesized that there would be good separation <br>
(ii) Just *Vitis* core species, no hybrids or *Ampelopsis* outgroup <br>
(iii) Just *Vitis* core and *Ampelopsis* outgroup, still no hybrids <br>
(iv) All species

In [3]:
# (i) rupestris and riparia
# create test set 
!python ~/GitHub/ML-Pipeline/test_set.py -df species_RupRip_prediction.csv -type c -p 0.1 -save RupRip_test_instances.csv -sep ','

Holding out 10.0 percent
Pulling test set from classes: ['Vitis_riparia' 'Vitis_rupestris']
257 instances in test set
finished!

In [37]:
# run model
!python  /Users/SLotreck/GitHub/ML-Pipeline/ML_classification.py -df species_RupRip_prediction.csv -test RupRip_test_instances.csv -cl_train Vitis_riparia,Vitis_rupestris -alg SVM -sep ',' -n 10 -gs_reps 5

Removing test instances to apply model on later...
Snapshot of data being used:
                  Class        x1        y1        x2        y2
Instance
2         Vitis_riparia  0.306808  0.799709  0.397394  0.774340
5         Vitis_riparia  0.366655  0.452072  0.448257  0.443414
6         Vitis_riparia  0.378910  0.649807  0.443035  0.646330
7         Vitis_riparia  0.302437  0.653963  0.377223  0.683326
8         Vitis_riparia  0.374232  0.677398  0.452144  0.662857


CLASSES: ['Vitis_riparia' 'Vitis_rupestris']
POS: Vitis_riparia type:  <class 'str'>
NEG: Vitis_rupestris type:  <class 'str'>

Balanced dataset will have 542 instances of each class


===>  Grid search started  <===
Round 1 of 5
Round 2 of 5
Round 3 of 5
Round 4 of 5
Round 5 of 5
Parameter sweep time: 23.127297 seconds
Parameters selected: Kernel=Linear, C=50.0
Grid search done. Time: 23.371360 s


===>  ML Pipeline started  <===
  Round 1 of 10
  Round 2 of 10
  Round 3 of 10
  Round 4 of 10
  Round 5 of 10
  Round 6 of 10
  Round 7 of 10
  Round 8 of 10
  Round 9 of 10
  Round 10 of 10
ML Pipeline time: 47.764597 seconds


===>  ML Results  <===

Validation Set Scores
Accuracy: 0.884963 (+/- stdev 0.004687)
F1: 0.885221 (+/- stdev 0.004813)
AUC-ROC: 0.944325 (+/- stdev 0.004606)
AUC-PRC: 0.945807 (+/- stdev 0.003033)


Test Set Scores:
Precision: 0.880074
Accuracy: 0.880074
F1: 0.880074
AUC-ROC: 0.939247 (+/- stdev 0.004607)
AUC-PRC: 0.976106 (+/- stdev 0.002869)
finished!

In [5]:
# (ii) Vitis core 
# create test set 
!python ~/GitHub/ML-Pipeline/test_set.py -df species_noOutgroupOrHybrids_prediction_dataset.csv -type c -p 0.1 -save Vitis_core_test_instances.csv -sep ','

Holding out 10.0 percent
Pulling test set from classes: ['Vitis_acerifolia' 'Vitis_aestivalis' 'Vitis_riparia' 'Vitis_vulpina'
 'Vitis_coignetiae' 'Vitis_labrusca' 'Vitis_cinerea' 'Vitis_rupestris'
 'Vitis_sp' 'Vitis_amurensis' 'Vitis_palmata']
559 instances in test set
finished!

In [38]:
# run model
!python  /Users/SLotreck/GitHub/ML-Pipeline/ML_classification.py -df species_noOutgroupOrHybrids_prediction_dataset.csv -test Vitis_core_test_instances.csv -alg SVM -sep ',' -n 10 -gs_reps 5

Removing test instances to apply model on later...
Snapshot of data being used:
                     Class        x1        y1        x2        y2
Instance
0         Vitis_acerifolia  0.395183  0.464763  0.462163  0.483590
1         Vitis_aestivalis  0.461953  0.676650  0.535271  0.714615
2            Vitis_riparia  0.404128  0.770275  0.471012  0.774340
3         Vitis_acerifolia  0.405337  0.789025  0.469997  0.798167
4         Vitis_aestivalis  0.319783  0.584354  0.333134  0.580537


CLASSES: ['Vitis_acerifolia' 'Vitis_aestivalis' 'Vitis_amurensis' 'Vitis_cinerea'
 'Vitis_coignetiae' 'Vitis_labrusca' 'Vitis_palmata' 'Vitis_riparia'
 'Vitis_rupestris' 'Vitis_sp' 'Vitis_vulpina']
POS: 1 type:  <class 'int'>
NEG: multiclass_no_NEG type:  <class 'str'>

Balanced dataset will have 53 instances of each class


===>  Grid search started  <===
Round 1 of 5
Round 2 of 5
Round 3 of 5
Round 4 of 5
Round 5 of 5
Parameter sweep time: 81.805566 seconds
Parameters selected: Kernel=Linear, C=10.0
Grid search done. Time: 82.025055 s


===>  ML Pipeline started  <===
  Round 1 of 10
  Round 2 of 10
  Round 3 of 10
  Round 4 of 10
  Round 5 of 10
  Round 6 of 10
  Round 7 of 10
  Round 8 of 10
  Round 9 of 10
  Round 10 of 10
ML Pipeline time: 204.374076 seconds

ML Results:
Accuracy: 0.491081 (+/- stdev 0.020455)
F1 (macro): 0.475926 (+/- stdev 0.022163)


ML Results from the test set :
Accuracy: 0.476844 (+/- stdev 0.000000)
F1 (macro): 0.394957 (+/- stdev 0.015999)

In [44]:
# (iii) Vitis core and Ampelopsis
# create test set 
!python ~/GitHub/ML-Pipeline/test_set.py -df species_noHybrids_prediction_dataset.csv -type c -p 0.1 -save Vitis_core_and_ampelopsis_test_instances.csv -sep ','

Holding out 10.0 percent
Pulling test set from classes: ['Vitis_acerifolia' 'Vitis_aestivalis' 'Vitis_riparia' 'Vitis_vulpina'
 'Vitis_coignetiae' 'Vitis_labrusca' 'Vitis_cinerea' 'Vitis_rupestris'
 'Vitis_sp' 'Vitis_amurensis' 'Vitis_palmata'
 'Ampelopsis_brevipedunculata']
561 instances in test set
finished!

In [45]:
# run model
!python  ~/GitHub/ML-Pipeline/ML_classification.py -df species_noHybrids_prediction_dataset.csv -test Vitis_core_and_ampelopsis_test_instances.csv -alg SVM -sep ',' -n 10 -gs_reps 5

Removing test instances to apply model on later...
Snapshot of data being used:
                     Class        x1        y1        x2        y2
Instance
0         Vitis_acerifolia  0.395183  0.464763  0.462163  0.483590
1         Vitis_aestivalis  0.461953  0.676650  0.535271  0.714615
2            Vitis_riparia  0.404128  0.770275  0.471012  0.774340
3         Vitis_acerifolia  0.405337  0.789025  0.469997  0.798167
4         Vitis_aestivalis  0.319783  0.584354  0.333134  0.580537


CLASSES: ['Ampelopsis_brevipedunculata' 'Vitis_acerifolia' 'Vitis_aestivalis'
 'Vitis_amurensis' 'Vitis_cinerea' 'Vitis_coignetiae' 'Vitis_labrusca'
 'Vitis_palmata' 'Vitis_riparia' 'Vitis_rupestris' 'Vitis_sp'
 'Vitis_vulpina']
POS: 1 type:  <class 'int'>
NEG: multiclass_no_NEG type:  <class 'str'>

Balanced dataset will have 18 instances of each class


===>  Grid search started  <===
Round 1 of 5
Round 2 of 5
Round 3 of 5
Round 4 of 5
Round 5 of 5
Parameter sweep time: 31.721418 seconds
Parameters selected: Kernel=Linear, C=1.0
Grid search done. Time: 31.817278 s


===>  ML Pipeline started  <===
  Round 1 of 10
  Round 2 of 10
  Round 3 of 10
  Round 4 of 10
  Round 5 of 10
  Round 6 of 10
  Round 7 of 10
  Round 8 of 10
  Round 9 of 10
  Round 10 of 10
ML Pipeline time: 59.672364 seconds

ML Results:
Accuracy: 0.420370 (+/- stdev 0.026900)
F1 (macro): 0.381825 (+/- stdev 0.028824)


ML Results from the test set :
Accuracy: 0.412037 (+/- stdev 0.000000)
F1 (macro): 0.316411 (+/- stdev 0.030225)

In [9]:
# (iv) All species
# create test set 
!python ~/GitHub/ML-Pipeline/test_set.py -df species_prediction_dataset.csv -type c -p 0.1 -save All_species_test_instances.csv -sep ','

Holding out 10.0 percent
Pulling test set from classes: ['Vitis_acerifolia' 'Vitis_aestivalis' 'Vitis_riparia' 'Vitis_vulpina'
 'Vitis_coignetiae' 'Vitis_labrusca' 'Vitis_cinerea' 'Vitis_x_doaniana'
 'Vitis_rupestris' 'Vitis_sp' 'Vitis_amurensis' 'Vitis_palmata'
 'Vitis_x_novae_angliae' 'Vitis_x_champinii' 'Vitis_x_andersonii'
 'Ampelopsis_brevipedunculata']
570 instances in test set
finished!

In [41]:
# run model
!python ~/GitHub/ML-Pipeline/ML_classification.py -df species_prediction_dataset.csv -test All_species_test_instances.csv -alg SVM -sep ',' -n 10 -gs_reps 5

Removing test instances to apply model on later...
Snapshot of data being used:
                     Class        x1        y1        x2        y2
Instance
0         Vitis_acerifolia  0.395183  0.464763  0.462163  0.477514
1         Vitis_aestivalis  0.461953  0.676650  0.535271  0.705636
2            Vitis_riparia  0.404128  0.770275  0.471012  0.764611
3         Vitis_acerifolia  0.405337  0.789025  0.469997  0.788139
5            Vitis_riparia  0.455573  0.435433  0.515661  0.437843


CLASSES: ['Ampelopsis_brevipedunculata' 'Vitis_acerifolia' 'Vitis_aestivalis'
 'Vitis_amurensis' 'Vitis_cinerea' 'Vitis_coignetiae' 'Vitis_labrusca'
 'Vitis_palmata' 'Vitis_riparia' 'Vitis_rupestris' 'Vitis_sp'
 'Vitis_vulpina' 'Vitis_x_andersonii' 'Vitis_x_champinii'
 'Vitis_x_doaniana' 'Vitis_x_novae_angliae']
POS: 1 type:  <class 'int'>
NEG: multiclass_no_NEG type:  <class 'str'>

Balanced dataset will have 15 instances of each class


===>  Grid search started  <===
Round 1 of 5
Round 2 of 5
Round 3 of 5
Round 4 of 5
Round 5 of 5
Parameter sweep time: 32.384067 seconds
Parameters selected: Kernel=Linear, C=1.0
Grid search done. Time: 32.493688 s


===>  ML Pipeline started  <===
  Round 1 of 10
  Round 2 of 10
  Round 3 of 10
  Round 4 of 10
  Round 5 of 10
  Round 6 of 10
  Round 7 of 10
  Round 8 of 10
  Round 9 of 10
  Round 10 of 10
ML Pipeline time: 49.142599 seconds

ML Results:
Accuracy: 0.404583 (+/- stdev 0.034179)
F1 (macro): 0.355367 (+/- stdev 0.047547)


ML Results from the test set :
Accuracy: 0.416667 (+/- stdev 0.000000)
F1 (macro): 0.214816 (+/- stdev 0.033137)

**2B. Predicting year**

In [35]:
# create test set 
!python ~/GitHub/ML-Pipeline/test_set.py -df year_strings_prediction_dataset.csv -type C -p 0.1 -save year_strings_test_instances.csv -sep ','

Holding out 10.0 percent
Pulling test set from classes: ['year2013' 'year2015' 'year2016']
570 instances in test set
finished!

In [36]:
# run model 
!python ~/GitHub/ML-Pipeline/ML_classification.py -df year_strings_prediction_dataset.csv -test year_strings_test_instances.csv -alg SVM -sep ',' -n 10 -gs_reps 5

Removing test instances to apply model on later...
Snapshot of data being used:
             Class        x1        y1        x2        y2
Instance
0         year2013  0.395183  0.464763  0.462163  0.477514
2         year2013  0.404128  0.770275  0.471012  0.764611
3         year2013  0.405337  0.789025  0.469997  0.788139
4         year2013  0.319783  0.584354  0.333134  0.573243
5         year2013  0.455573  0.435433  0.515661  0.437843


CLASSES: ['year2013' 'year2015' 'year2016']
POS: 1 type:  <class 'int'>
NEG: multiclass_no_NEG type:  <class 'str'>

Balanced dataset will have 1709 instances of each class


===>  Grid search started  <===
Round 1 of 5
Round 2 of 5
Round 3 of 5
Round 4 of 5
Round 5 of 5
Parameter sweep time: 474.676217 seconds
Parameters selected: Kernel=Linear, C=10.0
Grid search done. Time: 475.581961 s


===>  ML Pipeline started  <===
  Round 1 of 10
  Round 2 of 10
  Round 3 of 10
  Round 4 of 10
  Round 5 of 10
  Round 6 of 10
  Round 7 of 10
  Round 8 of 10
  Round 9 of 10
  Round 10 of 10
ML Pipeline time: 860.853867 seconds

ML Results:
Accuracy: 0.710708 (+/- stdev 0.000652)
F1 (macro): 0.707071 (+/- stdev 0.000676)


ML Results from the test set :
Accuracy: 0.710552 (+/- stdev 0.000000)
F1 (macro): 0.720556 (+/- stdev 0.001367)

**2C. Predicting node counted from base**

In [55]:
# create test set 
!python ~/GitHub/SL-ML-Pipeline/test_set.py -df nodes_from_base_strings_prediction_dataset.csv -type C -p 0.1 -save node_from_base_strings_test_instances.csv -sep ','

Holding out 10.0 percent
Pulling test set from classes: ['node10' 'node11' 'node12' 'node13' 'node1' 'node2' 'node3' 'node4'
 'node5' 'node6' 'node7' 'node8' 'node9']
572 instances in test set
finished!

In [56]:
# run model 
!python ~/GitHub/SL-ML-Pipeline/ML_classification.py -df nodes_from_base_strings_prediction_dataset.csv -test node_from_base_strings_test_instances.csv  -alg SVM -sep ',' -n 10 -gs_reps 5

Removing test instances to apply model on later...
Snapshot of data being used:
           Class        x1        y1        x2        y2
Instance
0         node10  0.395183  0.464763  0.462163  0.477514
1         node10  0.461953  0.676650  0.535271  0.705636
2         node10  0.404128  0.770275  0.471012  0.764611
3         node10  0.405337  0.789025  0.469997  0.788139
5         node10  0.455573  0.435433  0.515661  0.437843


CLASSES: ['node1' 'node10' 'node11' 'node12' 'node13' 'node2' 'node3' 'node4'
 'node5' 'node6' 'node7' 'node8' 'node9']
POS: 1 type:  <class 'int'>
NEG: multiclass_no_NEG type:  <class 'str'>

Balanced dataset will have 12 instances of each class


===>  Grid search started  <===
Round 1 of 5
Round 2 of 5
Round 3 of 5
Round 4 of 5
Round 5 of 5
Parameter sweep time: 25.907889 seconds
Parameters selected: Kernel=Linear, C=0.5
Grid search done. Time: 26.056402 s


===>  ML Pipeline started  <===
  Round 1 of 10
  Round 2 of 10
  Round 3 of 10
  Round 4 of 10
  Round 5 of 10
  Round 6 of 10
  Round 7 of 10
  Round 8 of 10
  Round 9 of 10
  Round 10 of 10
ML Pipeline time: 27.729919 seconds

ML Results:
Accuracy: 0.229487 (+/- stdev 0.022898)
F1 (macro): 0.176821 (+/- stdev 0.024910)


ML Results from the test set :
Accuracy: 0.243590 (+/- stdev 0.000000)
F1 (macro): 0.118206 (+/- stdev 0.021912)

**2D. Predicting node counted from tip**

In [57]:
# create test set 
!python ~/GitHub/SL-ML-Pipeline/test_set.py -df nodes_from_tip_strings_prediction_dataset.csv -type C -p 0.1 -save node_from_tip_strings_test_instances.csv -sep ','

Holding out 10.0 percent
Pulling test set from classes: ['node10' 'node11' 'node12' 'node13' 'node1' 'node2' 'node3' 'node4'
 'node5' 'node6' 'node7' 'node8' 'node9']
571 instances in test set
finished!

In [59]:
# run model 
!python /Users/SLotreck/GitHub/SL-ML-Pipeline/ML_classification.py -df nodes_from_tip_strings_prediction_dataset.csv -test node_from_tip_strings_test_instances.csv -alg SVM -sep ',' -n 10 -gs_reps 5

Removing test instances to apply model on later...
Snapshot of data being used:
           Class        x1        y1        x2        y2
Instance
0         node10  0.514585  0.511675  0.559305  0.556114
1         node10  0.459000  0.552941  0.495608  0.590639
2         node10  0.520725  0.745756  0.534521  0.819770
3         node10  0.570768  0.733037  0.578022  0.811013
4         node10  0.331083  0.556576  0.312998  0.624626


CLASSES: ['node1' 'node10' 'node11' 'node12' 'node13' 'node2' 'node3' 'node4'
 'node5' 'node6' 'node7' 'node8' 'node9']
POS: 1 type:  <class 'int'>
NEG: multiclass_no_NEG type:  <class 'str'>

Balanced dataset will have 12 instances of each class


===>  Grid search started  <===
Round 1 of 5
Round 2 of 5
Round 3 of 5
Round 4 of 5
Round 5 of 5
Parameter sweep time: 24.061487 seconds
Parameters selected: Kernel=Linear, C=10.0
Grid search done. Time: 24.187450 s


===>  ML Pipeline started  <===
  Round 1 of 10
  Round 2 of 10
  Round 3 of 10
  Round 4 of 10
  Round 5 of 10
  Round 6 of 10
  Round 7 of 10
  Round 8 of 10
  Round 9 of 10
  Round 10 of 10
ML Pipeline time: 58.681166 seconds

ML Results:
Accuracy: 0.192949 (+/- stdev 0.030264)
F1 (macro): 0.144383 (+/- stdev 0.024642)


ML Results from the test set :
Accuracy: 0.173077 (+/- stdev 0.000000)
F1 (macro): 0.118594 (+/- stdev 0.012096)

**Conclusions and closing notes** <br>
Performance metrics can be seen further in the output files ending in SVM_results.txt, and are also outlined in the powerpoint presentation. <br>
Overall, models for species and year perform quite well, whereas models for node prediction are not as successful. <br>
Note that, for multiclass models, the expectation for accuracy *and* for the F1 measure if the model were performing no better than random guessing, would be 1/(number of classes). For example, when predicting node, the expected F1 would be 1/13, or 0.0769. <br>
While the x-y coordinates perform quite well when differentiating species and year, it would be interesting to try these models with other types of features (perhaps persistent homology,or climate for the prediction of species or node) that may, when the importance of those features in prediction is determined, give us some biological insights to the mechanisms of leaf morhpology differences.